version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_pg
    volumes: 
      - ./db:/var/lib/postgresql/poc_logs
    env_file: .env
    expose:
      - 5432
    
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/home/app/
    depends_on:
      - db

volumes:
  db: